#!/bin/bash

if [ -z ${target} ] || [ -z "${command}" ]; then
	echo "Not all necessary variables are set." >&2
	echo "Please make sure the following variables are set:" >&2
	echo "target, command" >&2
	exit 1
fi

ssh $target "${command}" "${arguments}" || exitnr=$?

exit $exitnr