#!/bin/bash

if [ -z "${working_directory}" ]; then
	echo "Not all necessary variables are set." >&2
	echo "Please make sure the following variables are set:" >&2
	echo "working_directory" >&2
	exit 1
fi

cd ${working_directory}
if [ -z "${deploy_config}" ]; then
	deploy
else
	deploy -c ${deploy_config}
fi
