#!/bin/bash

if [ -z "${timeout}" ]; then
	echo "Not all necessary variables are set." >&2
	echo "Please make sure the following variables are set:" >&2
	echo "timeout" >&2
	exit 1
fi

echo "Press any key to continue (timeout: ${timeout}s)"
read -t ${timeout} -n 1